# Generated by Django 4.2.1 on 2023-06-03 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rank', models.CharField(max_length=30, verbose_name='Звання')),
                ('Rcount', models.FloatField(verbose_name='Кількість досвіду')),
            ],
        ),
        migrations.CreateModel(
            name='soldier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30, verbose_name='Позивний')),
                ('Age', models.IntegerField(verbose_name='Вік')),
                ('Gender', models.CharField(max_length=30, verbose_name='Стать')),
                ('EducationLevel', models.CharField(max_length=30, verbose_name='Рівень освіти')),
                ('ServiceDuration', models.IntegerField(verbose_name='Тривалість служби')),
                ('Contribution', models.FloatField(verbose_name='Досвід бійця')),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.rank')),
            ],
        ),
        migrations.CreateModel(
            name='specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Specialization', models.CharField(max_length=30, verbose_name='Спеціалізація')),
                ('Scount', models.FloatField(verbose_name='Кількість досвіду')),
            ],
        ),
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TaskType', models.CharField(max_length=30, verbose_name='Тип задачі')),
                ('DifficultyLevel', models.CharField(max_length=30, verbose_name='Рівень складності')),
                ('Duration', models.CharField(max_length=30, verbose_name='Тривалість')),
                ('Result', models.CharField(max_length=30, verbose_name='Результат')),
                ('Date', models.DateField(max_length=30, verbose_name='Дата виконання')),
                ('StartTime', models.TimeField(max_length=30, verbose_name='Час початку')),
                ('EndTime', models.TimeField(max_length=30, verbose_name='Час закінчення')),
                ('Location', models.CharField(max_length=30, verbose_name='Місце виконання')),
                ('WeatherConditions', models.CharField(max_length=30, verbose_name='Погодні умови')),
                ('Temperature', models.IntegerField(verbose_name='Температура')),
                ('Distance', models.CharField(max_length=30, verbose_name='Відстань')),
                ('Transport', models.CharField(max_length=30, verbose_name='Транспорт')),
            ],
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField()),
                ('soldier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.soldier')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.task')),
            ],
        ),
        migrations.AddField(
            model_name='soldier',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.specialization'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='tasks',
            field=models.ManyToManyField(through='main.TaskAssignment', to='main.task'),
        ),
    ]
