# Generated by Django 4.2.1 on 2023-06-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rank_soldier_specialization_task_taskassignment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20, verbose_name='Користувач')),
                ('password', models.FloatField(verbose_name='Пароль')),
            ],
        ),
    ]
