# Generated by Django 4.2.1 on 2023-06-06 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_loginform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loginform',
            old_name='user',
            new_name='username',
        ),
    ]
