# Generated by Django 4.2.1 on 2023-06-06 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_login_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.DeleteModel(
            name='squad',
        ),
    ]
