# Generated by Django 4.2.1 on 2023-06-07 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_squad_squadsoldiers_remove_soldier_tasks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='squadsoldiers',
            name='soldier',
        ),
        migrations.RemoveField(
            model_name='squadsoldiers',
            name='squad',
        ),
        migrations.RemoveField(
            model_name='soldier',
            name='squads',
        ),
        migrations.DeleteModel(
            name='Squad',
        ),
        migrations.DeleteModel(
            name='SquadSoldiers',
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='soldier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.soldier'),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.task'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='tasks',
            field=models.ManyToManyField(through='main.TaskAssignment', to='main.task'),
        ),
    ]
