# Generated by Django 4.2.1 on 2023-06-08 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_soldier_user_task_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soldier',
            old_name='Contribution',
            new_name='Experience',
        ),
    ]
