# Generated by Django 4.2.1 on 2023-06-13 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_contribution_soldier_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='difficultylevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DifficultyLevel', models.CharField(max_length=30, verbose_name='Складність')),
            ],
        ),
        migrations.CreateModel(
            name='transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Transport', models.CharField(max_length=225, verbose_name='Транспорт')),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='DifficultyLevel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.difficultylevel'),
        ),
        migrations.AlterField(
            model_name='task',
            name='Transport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.transport'),
        ),
    ]
