# Generated by Django 4.2.1 on 2023-06-13 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_difficultylevel_transport_alter_task_difficultylevel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rank',
            name='Rcount',
        ),
        migrations.RemoveField(
            model_name='specialization',
            name='Scount',
        ),
    ]
