# Generated by Django 4.2.1 on 2023-06-13 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_rank_rcount_remove_specialization_scount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soldier',
            name='Experience',
        ),
    ]
