# Generated by Django 4.2.1 on 2023-06-14 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_soldier_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='educationlevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EducationLevel', models.CharField(max_length=30, verbose_name='Рівень освіти')),
            ],
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(max_length=225, verbose_name='Місце виконання')),
            ],
        ),
        migrations.CreateModel(
            name='tasktype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TaskType', models.CharField(max_length=225, verbose_name='Тип задачі')),
            ],
        ),
        migrations.CreateModel(
            name='weatherconditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeatherConditions', models.CharField(max_length=225, verbose_name='Погодні умови')),
            ],
        ),
        migrations.AlterField(
            model_name='soldier',
            name='EducationLevel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.educationlevel'),
        ),
        migrations.AlterField(
            model_name='task',
            name='Location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.location'),
        ),
        migrations.AlterField(
            model_name='task',
            name='TaskType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tasktype'),
        ),
        migrations.AlterField(
            model_name='task',
            name='WeatherConditions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.weatherconditions'),
        ),
    ]
